//! Skin loading and drawing.
//!
//! A skin is a folder (or a zip of one) with a `skin.json` plus PNGs under
//! fixed names — see docs/SKINS.md. The base pastel skin is generated by
//! `cargo run --bin genskin` into `skins/base-pastel/` and embedded here, so
//! the app always has a complete skin; any file a user skin doesn't provide
//! falls back to the base one.

use crate::config::{NUM_SAMPLES, Theme, theme_light};
use egui::{
    Color32, Context, Painter, Pos2, Rect, TextureHandle, TextureOptions, TextureWrapMode, Vec2,
};
use serde::Deserialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

// ---- definition (skin.json) ----------------------------------------------

#[derive(Deserialize, Default)]
pub struct SkinDef {
    // name/author are catalog metadata; the app itself doesn't display them yet
    // (the in-app skin browser will).
    #[serde(default)]
    #[allow(dead_code)]
    pub name: String,
    #[serde(default)]
    #[allow(dead_code)]
    pub author: String,
    #[serde(default)]
    pub slice: SliceDef,
    /// Hex overrides ("#RRGGBB" or "#RRGGBBAA") for `Theme` fields, keyed by
    /// field name. Unknown keys are ignored.
    #[serde(default)]
    pub colors: HashMap<String, String>,
}

/// Nine-slice insets in source-image pixels.
#[derive(Deserialize, Clone, Copy)]
pub struct SliceDef {
    pub case: f32,
    pub bezel: f32,
}

impl Default for SliceDef {
    fn default() -> Self {
        Self {
            case: 96.0,
            bezel: 72.0,
        }
    }
}

// ---- loaded skin ---------------------------------------------------------

pub struct ButtonTex {
    pub idle: TextureHandle,
    pub pressed: TextureHandle,
}

pub struct Skin {
    pub background: TextureHandle,
    pub case: TextureHandle,
    /// Tileable matte grain, overlaid on the case centre (which nine-slice
    /// stretching leaves flat).
    pub grain: Option<TextureHandle>,
    pub bezel: TextureHandle,
    pub slice: SliceDef,
    pub pads: Vec<ButtonTex>,
    pub rec: ButtonTex,
    pub back: ButtonTex,
    pub cycle: ButtonTex,
    pub avatar_frame: TextureHandle,
    /// Colours for everything still drawn procedurally (visualizer, LEDs,
    /// text, the non-sampler screens).
    pub theme: Theme,
}

macro_rules! base_file {
    ($f:expr) => {
        include_bytes!(concat!("../../skins/base-pastel/", $f)).as_slice()
    };
}

/// Embedded bytes of the built-in base skin, by file name.
fn embedded(file: &str) -> &'static [u8] {
    macro_rules! table {
        ($($f:literal),+ $(,)?) => {
            match file { $($f => base_file!($f),)+ _ => unreachable!("unknown skin file {file}") }
        };
    }
    table!(
        "skin.json",
        "background.png",
        "case.png",
        "grain.png",
        "bezel.png",
        "avatar_frame.png",
        "pad_1.png",
        "pad_1_pressed.png",
        "pad_2.png",
        "pad_2_pressed.png",
        "pad_3.png",
        "pad_3_pressed.png",
        "pad_4.png",
        "pad_4_pressed.png",
        "pad_5.png",
        "pad_5_pressed.png",
        "pad_6.png",
        "pad_6_pressed.png",
        "pad_7.png",
        "pad_7_pressed.png",
        "pad_8.png",
        "pad_8_pressed.png",
        "pad_9.png",
        "pad_9_pressed.png",
        "pad_10.png",
        "pad_10_pressed.png",
        "pad_11.png",
        "pad_11_pressed.png",
        "pad_12.png",
        "pad_12_pressed.png",
        "rec.png",
        "rec_pressed.png",
        "back.png",
        "back_pressed.png",
        "cycle.png",
        "cycle_pressed.png",
    )
}

impl Skin {
    /// Load a skin from `dir`, falling back to the embedded base skin for any
    /// missing or unreadable file. `None` loads the base skin itself.
    pub fn load(ctx: &Context, dir: Option<&Path>) -> Self {
        let bytes = |file: &str| -> Vec<u8> {
            dir.and_then(|d| std::fs::read(d.join(file)).ok())
                .unwrap_or_else(|| embedded(file).to_vec())
        };
        let tex = |file: &str, opts: TextureOptions| -> TextureHandle {
            let data = bytes(file);
            let ci = crate::app::color_image_from_bytes(&data)
                .or_else(|| crate::app::color_image_from_bytes(embedded(file)))
                .expect("embedded skin image decodes");
            ctx.load_texture(format!("skin_{file}"), ci, opts)
        };
        let button = |name: &str| -> ButtonTex {
            ButtonTex {
                idle: tex(&format!("{name}.png"), TextureOptions::LINEAR),
                pressed: tex(&format!("{name}_pressed.png"), TextureOptions::LINEAR),
            }
        };

        let def: SkinDef = serde_json::from_slice(&bytes("skin.json")).unwrap_or_else(|e| {
            eprintln!("skin.json invalid ({e}), using defaults");
            serde_json::from_slice(embedded("skin.json")).expect("embedded skin.json parses")
        });

        let mut theme = theme_light();
        apply_colors(&mut theme, &def.colors);

        let grain_opts = TextureOptions {
            wrap_mode: TextureWrapMode::Repeat,
            ..TextureOptions::LINEAR
        };

        Self {
            background: tex("background.png", TextureOptions::LINEAR),
            case: tex("case.png", TextureOptions::LINEAR),
            grain: Some(tex("grain.png", grain_opts)),
            bezel: tex("bezel.png", TextureOptions::LINEAR),
            slice: def.slice,
            pads: (1..=NUM_SAMPLES)
                .map(|i| button(&format!("pad_{i}")))
                .collect(),
            rec: button("rec"),
            back: button("back"),
            cycle: button("cycle"),
            avatar_frame: tex("avatar_frame.png", TextureOptions::LINEAR),
            theme,
        }
    }
}

// ---- discovery -----------------------------------------------------------

/// Where user skins live: `<config>/rondelek/skins/<name>/skin.json`.
pub fn skins_dir() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("rondelek")
        .join("skins")
}

/// List installed skins. Any `.zip` dropped into the skins dir is extracted
/// to a folder of the same name first, so zips are the distribution format
/// and folders are the installed one.
pub fn discover() -> Vec<String> {
    discover_in(&skins_dir())
}

fn discover_in(dir: &Path) -> Vec<String> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let entries: Vec<_> = entries.flatten().collect();

    for e in &entries {
        let path = e.path();
        if path.extension().is_some_and(|x| x == "zip")
            && let Some(stem) = path.file_stem()
            && !dir.join(stem).exists()
            && let Err(err) = extract_zip(&path, &dir.join(stem))
        {
            eprintln!("failed to extract skin {}: {err}", path.display());
        }
    }

    let mut names: Vec<String> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .filter(|e| e.path().join("skin.json").is_file())
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    names.sort();
    names
}

fn extract_zip(zip_path: &Path, dest: &Path) -> anyhow::Result<()> {
    let file = std::fs::File::open(zip_path)?;
    let mut archive = zip::ZipArchive::new(file)?;
    archive.extract(dest)?;
    // Tolerate zips that wrap everything in a single top-level folder.
    if !dest.join("skin.json").is_file()
        && let Ok(mut inner) = std::fs::read_dir(dest)
        && let Some(Ok(only)) = inner.next()
        && only.path().join("skin.json").is_file()
    {
        for e in std::fs::read_dir(only.path())?.flatten() {
            std::fs::rename(e.path(), dest.join(e.file_name()))?;
        }
    }
    Ok(())
}

// ---- drawing helpers -----------------------------------------------------

fn uv(x0: f32, y0: f32, x1: f32, y1: f32) -> Rect {
    Rect::from_min_max(Pos2::new(x0, y0), Pos2::new(x1, y1))
}

pub fn uv_full() -> Rect {
    uv(0.0, 0.0, 1.0, 1.0)
}

/// On-screen corner size for a nine-slice draw of `tex` into `rect`.
pub fn slice_screen_inset(inset_px: f32, rect: Rect) -> f32 {
    inset_px.min(rect.width() / 2.5).min(rect.height() / 2.5)
}

/// Draw `tex` into `rect` as a nine-slice: corners stay unscaled (`inset_px`
/// source pixels), edges stretch along one axis, the centre along both.
pub fn draw_nine_slice(p: &Painter, tex: &TextureHandle, rect: Rect, inset_px: f32) {
    let ts = tex.size_vec2();
    let d = slice_screen_inset(inset_px, rect);
    let (su, sv) = (inset_px / ts.x, inset_px / ts.y);
    let xs = [rect.left(), rect.left() + d, rect.right() - d, rect.right()];
    let ys = [rect.top(), rect.top() + d, rect.bottom() - d, rect.bottom()];
    let us = [0.0, su, 1.0 - su, 1.0];
    let vs = [0.0, sv, 1.0 - sv, 1.0];
    for i in 0..3 {
        for j in 0..3 {
            p.image(
                tex.id(),
                Rect::from_min_max(Pos2::new(xs[i], ys[j]), Pos2::new(xs[i + 1], ys[j + 1])),
                uv(us[i], vs[j], us[i + 1], vs[j + 1]),
                Color32::WHITE,
            );
        }
    }
}

/// Draw `tex` covering `rect`: uniformly scaled to fill, centre-cropped.
pub fn draw_cover(p: &Painter, tex: &TextureHandle, rect: Rect) {
    let ts = tex.size_vec2();
    let scale = (rect.width() / ts.x).max(rect.height() / ts.y);
    let visible = Vec2::new(rect.width(), rect.height()) / (ts * scale);
    p.image(
        tex.id(),
        rect,
        Rect::from_center_size(Pos2::new(0.5, 0.5), visible),
        Color32::WHITE,
    );
}

/// Tile `tex` (loaded with `TextureWrapMode::Repeat`) across `rect` at 1:1.
pub fn draw_tiled(p: &Painter, tex: &TextureHandle, rect: Rect) {
    let ts = tex.size_vec2();
    p.image(
        tex.id(),
        rect,
        uv(0.0, 0.0, rect.width() / ts.x, rect.height() / ts.y),
        Color32::WHITE,
    );
}

// ---- theme colours -------------------------------------------------------

fn parse_hex(s: &str) -> Option<Color32> {
    let s = s.trim_start_matches('#');
    match s.len() {
        6 => {
            let v = u32::from_str_radix(s, 16).ok()?;
            Some(Color32::from_rgb((v >> 16) as u8, (v >> 8) as u8, v as u8))
        }
        8 => {
            let v = u32::from_str_radix(s, 16).ok()?;
            Some(Color32::from_rgba_unmultiplied(
                (v >> 24) as u8,
                (v >> 16) as u8,
                (v >> 8) as u8,
                v as u8,
            ))
        }
        _ => None,
    }
}

fn apply_colors(theme: &mut Theme, colors: &HashMap<String, String>) {
    for (key, value) in colors {
        let Some(c) = parse_hex(value) else {
            eprintln!("skin colour {key}: bad value {value:?}");
            continue;
        };
        match key.as_str() {
            "panel_bg" => theme.panel_bg = c,
            "panel_fg" => theme.panel_fg = c,
            "pad_play_bg" => theme.pad_play_bg = c,
            "pad_play_fg" => theme.pad_play_fg = c,
            "pad_play_hover" => theme.pad_play_hover = c,
            "pad_play_pressed" => theme.pad_play_pressed = c,
            "pad_record_bg" => theme.pad_record_bg = c,
            "pad_record_fg" => theme.pad_record_fg = c,
            "pad_function_bg" => theme.pad_function_bg = c,
            "pad_function_fg" => theme.pad_function_fg = c,
            "led_empty" => theme.led_empty = c,
            "led_full" => theme.led_full = c,
            "case_shadow" => theme.case_shadow = c,
            "case_border" => theme.case_border = c,
            "text_primary" => theme.text_primary = c,
            "text_secondary" => theme.text_secondary = c,
            "visualizer_bg" => theme.visualizer_bg = c,
            "visualizer_dot_off" => theme.visualizer_dot_off = c,
            "visualizer_bar_low" => theme.visualizer_bar_low = c,
            "visualizer_bar_mid" => theme.visualizer_bar_mid = c,
            "visualizer_bar_high" => theme.visualizer_bar_high = c,
            _ => eprintln!("skin colour {key}: unknown key"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_parses_rgb_and_rgba() {
        assert_eq!(
            parse_hex("#FF6A1A"),
            Some(Color32::from_rgb(0xFF, 0x6A, 0x1A))
        );
        assert_eq!(
            parse_hex("00000028"),
            Some(Color32::from_rgba_unmultiplied(0, 0, 0, 0x28))
        );
        assert_eq!(parse_hex("#nope"), None);
    }

    #[test]
    fn base_skin_json_parses_and_all_colors_apply() {
        let def: SkinDef = serde_json::from_slice(embedded("skin.json")).unwrap();
        assert_eq!(def.name, "Base Pastel");
        assert_eq!(def.slice.case, 96.0);
        let mut theme = theme_light();
        apply_colors(&mut theme, &def.colors);
        assert_eq!(theme.visualizer_bg, Color32::from_rgb(0x33, 0x30, 0x3A));
    }

    #[test]
    fn zip_in_skins_dir_is_extracted_and_discovered() {
        use std::io::Write;
        let dir = std::env::temp_dir().join(format!("rondelek-skin-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let file = std::fs::File::create(dir.join("my-skin.zip")).unwrap();
        let mut z = zip::ZipWriter::new(file);
        let opts: zip::write::SimpleFileOptions = Default::default();
        z.start_file("skin.json", opts).unwrap();
        z.write_all(b"{\"name\":\"My Skin\"}").unwrap();
        z.finish().unwrap();

        assert_eq!(discover_in(&dir), vec!["my-skin".to_string()]);
        assert!(dir.join("my-skin/skin.json").is_file());
        // Idempotent: a second scan doesn't re-extract or duplicate.
        assert_eq!(discover_in(&dir), vec!["my-skin".to_string()]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn embedded_images_decode() {
        for f in ["background.png", "case.png", "pad_1.png", "rec_pressed.png"] {
            assert!(
                crate::app::color_image_from_bytes(embedded(f)).is_some(),
                "{f}"
            );
        }
    }
}
